logs:
  - name: root
    level: DEBUG
    formatter: "%d%T[%p]%T%m%n"
    appenders: 
      - type: FileLogAppender
        level: DEBUG
        file: ../log/root_log.txt
      - type: SoutLogAppender
        level: INFO
  - name: system
    level: DEBUG
    formatter: "%d%T[%p]%T%m%n"
    appenders:
      - type: FileLogAppender
        level: INFO
        file: ../log/system_log.txt
      - type: SoutLogAppender
        level: INFO
class:
  name: ggy
  age: 10