logs:
  - name: root
    level: DEBUG
    appenders: 
      - type: FileLogAppender
        level: DEBUG
        file: ../log/root_log.txt
      - type: SoutLogAppender
        level: INFO
  - name: system
    level: DEBUG
    formatter: "%d{%Y-%m-%d %H:%M:%S}%T%N:%t%T%C%T%[%c][%p]%T(%f:%l)%T%m%n"
    appenders:
      - type: FileLogAppender
        level: INFO
        file: ../log/system_log.txt
      - type: SoutLogAppender
        level: INFO