logs:
  - name: root
    level: DEBUG
    formatter: "%d%T[%p]%T%m%n"
    appenders: 
      - type: FileLogAppender
        level: DEBUG
        file: ../log/root_log.txt
      - type: SoutLogAppender
        level: INFO
  - name: system
    level: DEBUG
    formatter: "%d%T%m%n"
    appenders:
      - type: FileLogAppender
        level: INFO
        file: ../log/system_log.txt
        formatter: "%d%T[%p]%T%m%n"
      - type: SoutLogAppender
        level: INFO
        formatter: "%d%T[%p]%T%m%n"