logs:
  - name: root
    level: INFO
    formatter: "%d%T%n"
    appenders: 
      - type: FileLogAppender
        file: ../log/root_log.txt
      - type: SoutLogAppender
  - name: system
    level: DEBUG
    formatter: "%d%T%m%n"
    appenders:
      - type: FileLogAppender
        file: ../log/system_log.txt
        formatter: "%d%T[%p]%m%n"
      - type: SoutLogAppender